# print('1')
# print('2')
# print('3')
# print('4')
# print('5')
# print('6')
# print('7')
# print('8')
# print('9')
# print('10')

for num in range(1, 1001):
    print(num)
    print('line 1')
    print('line 2')